<a href="https://colab.research.google.com/github/fk-2code/Titanic/blob/main/Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

student = pd.DataFrame({'Name': ['Limiya', 'Ferha', 'Rihanna', 'Eman','Tesnim', 'Rim', 'RUqia', 'Semira', 'Newal', 'Ekram','Ayah', 'Ahmed', 'Kemal', 'Ansuar','Mohammed'], 'Age': [22, 21, 18, 19, 20, 19, 20, 20, 20, 19, 23, 24, 23, 25, 26], 'Departnemt': ['CSE', 'SWE', 'Mechanical', 'Civil', 'SWE', 'Pharmacy', 'Power', 'Pharmacy', 'Pharmacy', 'Chemistry', 'CSE', 'Architecture', 'Civil', 'Comunication','Mechanical'], 'YEAR': [1, 1, 3, 1, 2, 2, 2, 2, 2, 2, 4, 5, 3, 3, 5], 'CGPA': [3.44, 3.56, 3.7, 3.18, 3.23, 3.30, 3.65, 3.29, 3.14, 3.89, 3.9, 2.98, 3.50, 2.7, 3.66]}, index = ['UGR/23456/18', 'UGR/34678/18', 'UGR/25697/16', 'UGR/21879/18', 'UGR/12456/17', 'UGR/45765/17', 'UGR/12475/17', 'UGR/46753/17', 'UGR/45732/17', 'UGR/37896/17', 'UGR/23789/15', 'UGR/38657/14', 'UGR/34251/16', 'UGR/35679/16',  'UGR/24356/14'])

print(student)

                  Name  Age    Departnemt  YEAR  CGPA
UGR/23456/18    Limiya   22           CSE     1  3.44
UGR/34678/18     Ferha   21           SWE     1  3.56
UGR/25697/16   Rihanna   18    Mechanical     3  3.70
UGR/21879/18      Eman   19         Civil     1  3.18
UGR/12456/17    Tesnim   20           SWE     2  3.23
UGR/45765/17       Rim   19      Pharmacy     2  3.30
UGR/12475/17     RUqia   20         Power     2  3.65
UGR/46753/17    Semira   20      Pharmacy     2  3.29
UGR/45732/17     Newal   20      Pharmacy     2  3.14
UGR/37896/17     Ekram   19     Chemistry     2  3.89
UGR/23789/15      Ayah   23           CSE     4  3.90
UGR/38657/14     Ahmed   24  Architecture     5  2.98
UGR/34251/16     Kemal   23         Civil     3  3.50
UGR/35679/16    Ansuar   25  Comunication     3  2.70
UGR/24356/14  Mohammed   26    Mechanical     5  3.66

## Exploration

In [5]:
df=pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

##  Data Cleaning

In [7]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop(columns=["Cabin"])

df.drop_duplicates()

df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## Data Analysis

In [8]:
print(df.groupby("Sex")["Survived"].mean())
print(df.groupby("Pclass")["Survived"].mean())
print(df.groupby("Pclass")["Age"].mean())

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64
Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

In [10]:
df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 12, 18, 60, 100], labels=['Child', 'Teen', 'Adult', 'Senior'])
print(df.groupby('AgeGroup', observed=False)['Survived'].mean())

AgeGroup
Child     0.579710
Teen      0.428571
Adult     0.365753
Senior    0.227273
Name: Survived, dtype: float64

## Filtering

In [12]:
females_survived = df[(df['Sex'] == 'female') & (df['Survived'] == 1)]

females_survived.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,Teen

In [13]:
children_survived = df[(df['Age'] < 18) & (df['Survived'] == 1)]

children_survived.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,Teen
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S,Child
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,Q,Teen
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,C,Teen
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,C,Child

In [14]:
first_class_survived = df[(df['Pclass'] == 1) & (df["Survived"] == 1)]

first_class_survived.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Adult
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S,Adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,C,Adult

## Insights


*   Females had a significantly higher survival ratr than male.
*   Yes. Passengers in 1st class had the highest survival rate, followed by 2nd, with 3rd class having the lowest.
*   Generally, yes. The survival rate for the Child age group is typically higher than for the Adults.
*   Females in the 1st class usually represent the group with the highest survival probability, often exceeding 90%.